# Generated by Django 4.2.1 on 2023-05-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mock_profiles_creation'),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE core_connection AUTO_INCREMENT = 1;            
            INSERT INTO core_connection (id1_id, id2_id) VALUES (1, 3);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (3, 1);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (1, 4);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (4, 1);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (5, 2);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (2, 5);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (5, 3);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (3, 5);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (5, 4);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (4, 5);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (5, 6);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (6, 5);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (6, 7);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (7, 6);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (2, 7);
            INSERT INTO core_connection (id1_id, id2_id) VALUES (7, 2);
        """, """
            DELETE FROM core_connection;
        """)
    ]